spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planifCours?useSSL=false&serverTimezone=UTC
    username: planif
    password: planifIsm2023
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      #ddl-auto: create
      #ddl-auto: validate