
server:
  port: 9995
spring:
  datasource:
    url: jdbc:mysql://localhost:8889/planifCours?createTableIfNotExist=true
    username: planif
    password: planifCoursIsm2023
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      #show-sql: true
      #ddl-auto: update
      #ddl-auto: create
      ddl-auto: validate